version: "2"

services:
  ui:
    image: msf-ui
    ports:
      - "80:80"
    networks:
      - msf
  api:
    image: msf-api
    ports:
      - "8013:8013"
    networks:
      - msf
    volumes:
      - dbdata:/app/db

networks:
  msf:

volumes:
  dbdata:
    external: true
